### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by LokyStaz** [Eole211/HumShare#1]
Nothing happen after activated !! After activated in admin. I can activate this module in profile, but nothing happen then !!

**Comment by Eole211** [comment]
This module in meant to be used in spaces. You have to add it to a space to use it. Also, everything is only in french for now...

**Comment by LokyStaz** [comment]
Ah ok... Je suis français !! ^^ PAS de Doc!!!!
Du coup pourrais-tu prendre 5 min pour m'expliquer ce module.... Je ne comprend pas le principe... C'est quoi des trucs? C'est quoi la difference avec un post? Partager quoi avec qui ? (c'est public, privé?)

Et si je peux me permettre, comme apparemment les users peuvent voir leurs "trucs" sur une page spécial, du coup se serait bien d'avoir access à "mes truc partagé" dans le profile non ??

(Désolé j'ai un peut du mal en français !! ^^)

**Comment by Eole211** [comment]
Le but du module est que chaque membre de l'espace ajoute les objets (les fameux trucs ) qu'il souhaite mettre à disposition des autres membres. Chaque objet appartient à une catégorie, les catégories pouvant être éditées par les administrateurs et modérateurs de l'espace. 
La zone de recherche permet aux membres de rechercher des trucs. Si une recherche vide est lancée, tout les objets de la catégorie sélectionnée vont s'afficher.
Sinon, oui, c'est prévu que les utilisateurs aient un accès à leurs trucs partagés depuis leur profil dans les prochaines versions. Il y aura aussi bientôt la possibilité d'ajouter son numéro de téléphone quand on prête un truc.
